services:
  - type: web
    runtime: node
    name: survey-app
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "1"
      - key: MONGODB_URI
        sync: false  # Set this manually in Render dashboard
      - key: ALLOWED_ORIGINS
        sync: false  # Set this manually in Render dashboard
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: true